import type { AnalyseResult } from "@/lib/types";

import p0 from "./zafar-hasan-v2-28";
import p1 from "./zafar-hasan-v2-264";
import p2 from "./zafar-hasan-v2-280";
import p3 from "./zafar-hasan-v2-292";

// generated by scripts/build-discovery-cache.ts
export const DISCOVERY_CACHE: Record<string, AnalyseResult> = {
  "zafar-hasan-v2-28": p0,
  "zafar-hasan-v2-264": p1,
  "zafar-hasan-v2-280": p2,
  "zafar-hasan-v2-292": p3,
};
