import type { AnalyseResult } from "@/lib/types";

import p0 from "./zafar-hasan-v2-28";
import p1 from "./zafar-hasan-v2-32";
import p2 from "./zafar-hasan-v2-35";
import p3 from "./zafar-hasan-v2-45";
import p4 from "./zafar-hasan-v2-55";
import p5 from "./zafar-hasan-v2-58";
import p6 from "./zafar-hasan-v2-59";
import p7 from "./zafar-hasan-v2-60";
import p8 from "./zafar-hasan-v2-61";
import p9 from "./zafar-hasan-v2-64";
import p10 from "./zafar-hasan-v2-65";
import p11 from "./zafar-hasan-v2-67";
import p12 from "./zafar-hasan-v2-68";
import p13 from "./zafar-hasan-v2-73";
import p14 from "./zafar-hasan-v2-75";
import p15 from "./zafar-hasan-v2-76";
import p16 from "./zafar-hasan-v2-77";
import p17 from "./zafar-hasan-v2-79";
import p18 from "./zafar-hasan-v2-122";
import p19 from "./zafar-hasan-v2-129";
import p20 from "./zafar-hasan-v2-130";
import p21 from "./zafar-hasan-v2-133";
import p22 from "./zafar-hasan-v2-145";
import p23 from "./zafar-hasan-v2-149";
import p24 from "./zafar-hasan-v2-196";
import p25 from "./zafar-hasan-v2-198";
import p26 from "./zafar-hasan-v2-200";
import p27 from "./zafar-hasan-v2-202";
import p28 from "./zafar-hasan-v2-236";
import p29 from "./zafar-hasan-v2-241";
import p30 from "./zafar-hasan-v2-242";
import p31 from "./zafar-hasan-v2-246";
import p32 from "./zafar-hasan-v2-253";
import p33 from "./zafar-hasan-v2-264";

// generated by scripts/build-discovery-cache.ts
export const DISCOVERY_CACHE: Record<string, AnalyseResult> = {
  "zafar-hasan-v2-28": p0,
  "zafar-hasan-v2-32": p1,
  "zafar-hasan-v2-35": p2,
  "zafar-hasan-v2-45": p3,
  "zafar-hasan-v2-55": p4,
  "zafar-hasan-v2-58": p5,
  "zafar-hasan-v2-59": p6,
  "zafar-hasan-v2-60": p7,
  "zafar-hasan-v2-61": p8,
  "zafar-hasan-v2-64": p9,
  "zafar-hasan-v2-65": p10,
  "zafar-hasan-v2-67": p11,
  "zafar-hasan-v2-68": p12,
  "zafar-hasan-v2-73": p13,
  "zafar-hasan-v2-75": p14,
  "zafar-hasan-v2-76": p15,
  "zafar-hasan-v2-77": p16,
  "zafar-hasan-v2-79": p17,
  "zafar-hasan-v2-122": p18,
  "zafar-hasan-v2-129": p19,
  "zafar-hasan-v2-130": p20,
  "zafar-hasan-v2-133": p21,
  "zafar-hasan-v2-145": p22,
  "zafar-hasan-v2-149": p23,
  "zafar-hasan-v2-196": p24,
  "zafar-hasan-v2-198": p25,
  "zafar-hasan-v2-200": p26,
  "zafar-hasan-v2-202": p27,
  "zafar-hasan-v2-236": p28,
  "zafar-hasan-v2-241": p29,
  "zafar-hasan-v2-242": p30,
  "zafar-hasan-v2-246": p31,
  "zafar-hasan-v2-253": p32,
  "zafar-hasan-v2-264": p33,
};
