import type { AnalyseResult } from "@/lib/types";

import p0 from "./zafar-hasan-v2-28";
import p1 from "./zafar-hasan-v2-32";
import p2 from "./zafar-hasan-v2-35";
import p3 from "./zafar-hasan-v2-45";
import p4 from "./zafar-hasan-v2-55";
import p5 from "./zafar-hasan-v2-58";
import p6 from "./zafar-hasan-v2-59";
import p7 from "./zafar-hasan-v2-60";
import p8 from "./zafar-hasan-v2-61";
import p9 from "./zafar-hasan-v2-64";
import p10 from "./zafar-hasan-v2-65";
import p11 from "./zafar-hasan-v2-67";
import p12 from "./zafar-hasan-v2-73";
import p13 from "./zafar-hasan-v2-76";
import p14 from "./zafar-hasan-v2-77";
import p15 from "./zafar-hasan-v2-122";
import p16 from "./zafar-hasan-v2-129";
import p17 from "./zafar-hasan-v2-130";
import p18 from "./zafar-hasan-v2-145";
import p19 from "./zafar-hasan-v2-198";
import p20 from "./zafar-hasan-v2-236";

// generated by scripts/build-discovery-cache.ts
export const DISCOVERY_CACHE: Record<string, AnalyseResult> = {
  "zafar-hasan-v2-28": p0,
  "zafar-hasan-v2-32": p1,
  "zafar-hasan-v2-35": p2,
  "zafar-hasan-v2-45": p3,
  "zafar-hasan-v2-55": p4,
  "zafar-hasan-v2-58": p5,
  "zafar-hasan-v2-59": p6,
  "zafar-hasan-v2-60": p7,
  "zafar-hasan-v2-61": p8,
  "zafar-hasan-v2-64": p9,
  "zafar-hasan-v2-65": p10,
  "zafar-hasan-v2-67": p11,
  "zafar-hasan-v2-73": p12,
  "zafar-hasan-v2-76": p13,
  "zafar-hasan-v2-77": p14,
  "zafar-hasan-v2-122": p15,
  "zafar-hasan-v2-129": p16,
  "zafar-hasan-v2-130": p17,
  "zafar-hasan-v2-145": p18,
  "zafar-hasan-v2-198": p19,
  "zafar-hasan-v2-236": p20,
};
