import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 76,
  "mentions": [
    {
      "id": "m_76_1",
      "name": "An enclosure with two gateways.",
      "type": "other",
      "period": "Mughal",
      "passage": "(b) Immediately to the north of Katra Iradatmand Khan Xo. 95.",
      "passageOffset": [
        66,
        127
      ],
      "spatialClue": {
        "anchorName": "Katra Iradatmand Khan",
        "bearing": "N",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_76_2",
      "name": "Katra Iradatmand Khan",
      "type": "gateway",
      "period": "Mughal period",
      "passage": "(b) Some 100 yards to the west of No. 200, outside Kotla Nizamuddin.",
      "passageOffset": [
        596,
        664
      ],
      "spatialClue": {
        "anchorName": "Kotla Nizamuddin",
        "bearing": "W",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_76_3",
      "name": "Tomb (unknown)",
      "type": "tomb",
      "period": "Mughal,",
      "passage": "(b) Some 33 yards to the east of Katra Iradatmand Khan No. 95.",
      "passageOffset": [
        1368,
        1430
      ],
      "spatialClue": {
        "anchorName": "Katra Iradatmand Khan",
        "bearing": "E",
        "distanceValue": 33,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
