import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 200,
  "mentions": [
    {
      "id": "m_200_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Late Mughal",
      "passage": "Some 300 yards off the S&fdar Jang-Humayun’s Tomb road, to the south.",
      "passageOffset": [
        73,
        142
      ],
      "spatialClue": {
        "anchorName": "S&fdar Jang-Humayun’s Tomb road",
        "bearing": "S",
        "distanceValue": 300,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_200_2",
      "name": "Unknown",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 25 paces to the west of No. 246.",
      "passageOffset": [
        461,
        498
      ],
      "spatialClue": {
        "anchorName": "No. 246",
        "bearing": "W",
        "distanceValue": 25,
        "distanceUnit": "paces"
      }
    },
    {
      "id": "m_200_3",
      "name": "Unknown",
      "type": "mosque",
      "period": "Mughal",
      "passage": "By the Great Indian Peninsula Railway line. Some 300 yards to the south of No. 246.",
      "passageOffset": [
        1066,
        1149
      ],
      "spatialClue": {
        "anchorName": "Great Indian Peninsula Railway line",
        "bearing": "S",
        "distanceValue": 300,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
