import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 252,
  "mentions": [
    {
      "id": "m_252_1",
      "name": "Boli Bhatyari ka Mahall",
      "type": "palace",
      "period": "755 A.H. (1354 A.D.)",
      "passage": "The palace stands at the southern end of the bund",
      "passageOffset": [
        23,
        72
      ],
      "spatialClue": {
        "anchorName": "bund",
        "bearing": "S",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_252_2",
      "name": "Grave of Khuda Numa",
      "type": "tomb",
      "period": "1106 A.H. (1694-5 A.D.)",
      "passage": "Some 200 yards from Boli Bhatyari ka Mahall (No. 337), towards the north.",
      "passageOffset": [
        1305,
        1378
      ],
      "spatialClue": {
        "anchorName": "Boli Bhatyari ka Mahall",
        "bearing": "N",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_252_2",
      "mentionId": "m_252_2",
      "centroid": [
        77.20385,
        28.643394677081176
      ],
      "uncertaintyRadiusM": 403.1833762867916,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.5475,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.25,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "bhuli-bhatiyari",
        "anchorName": "Bhuli Bhatiyari ka Mahal",
        "anchorSource": "approximate",
        "anchorCentroid": [
          77.20385,
          28.64175
        ],
        "bearingDeg": 0,
        "distanceM": 182.88,
        "radiusParts": {
          "anchorPrecisionM": 300,
          "bearingSpreadM": 75.75137628679161,
          "distanceVaguenessM": 27.432,
          "floorTopUpM": 0
        },
        "baselineVerdict": "representation_gap",
        "baselineChecked": [
          {
            "id": "w1121647750",
            "name": "Fariha Jame Mosque",
            "distanceM": 582.7737710630289,
            "insideRadius": false
          },
          {
            "id": "n12839661856",
            "name": "unnamed no (n12839661856)",
            "distanceM": 630.8313643260653,
            "insideRadius": false
          },
          {
            "id": "n10278723609",
            "name": "Albero nel muro",
            "distanceM": 682.8376149676961,
            "insideRadius": false
          },
          {
            "id": "n12839662481",
            "name": "unnamed no (n12839662481)",
            "distanceM": 689.9562430710197,
            "insideRadius": false
          },
          {
            "id": "n5389381021",
            "name": "Snooker tashi",
            "distanceM": 922.4002164827172,
            "insideRadius": false
          }
        ]
      }
    }
  ]
};

export default page;
