import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 68,
  "mentions": [
    {
      "id": "m_68_1",
      "name": "Unknown",
      "type": "tomb",
      "period": null,
      "passage": "",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": null
    },
    {
      "id": "m_68_2",
      "name": "Unknown",
      "type": "gateway",
      "period": null,
      "passage": "At the distance of some 36 yards towards the west stands a massive gateway which formed the entrance to the enclosure surrounding the tomb.",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "tomb",
        "bearing": "W",
        "distanceValue": 36,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_68_3",
      "name": "Unknown",
      "type": "tomb",
      "period": "Afghan period",
      "passage": "Some 140 yards to the south of No. 78.",
      "passageOffset": [
        911,
        949
      ],
      "spatialClue": {
        "anchorName": "No. 78",
        "bearing": "S",
        "distanceValue": 140,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_68_4",
      "name": "Grave of Hazrat Bibi Fatima Sam",
      "type": "tomb",
      "period": null,
      "passage": "Some 400 yards to the S.-W. of Khair-ul-Manazil No. 83.",
      "passageOffset": [
        1317,
        1372
      ],
      "spatialClue": {
        "anchorName": "Khair-ul-Manazil No. 83",
        "bearing": "SW",
        "distanceValue": 400,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
