import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 202,
  "mentions": [
    {
      "id": "m_202_1",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 150 paces south-west of No. 247.",
      "passageOffset": [
        487,
        524
      ],
      "spatialClue": {
        "anchorName": "No. 247",
        "bearing": "SW",
        "distanceValue": 150,
        "distanceUnit": "paces"
      }
    },
    {
      "id": "m_202_2",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "Some 500 yards S. W. of No. 251.",
      "passageOffset": [
        1087,
        1119
      ],
      "spatialClue": {
        "anchorName": "No. 251",
        "bearing": "SW",
        "distanceValue": 500,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_202_3",
      "name": "Unknown",
      "type": "tomb",
      "period": null,
      "passage": "Some 100 yards to the north of No. 252.",
      "passageOffset": [
        1718,
        1757
      ],
      "spatialClue": {
        "anchorName": "No. 252",
        "bearing": "N",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
