import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 145,
  "mentions": [
    {
      "id": "m_145_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "112 yards south of No. 165.",
      "passageOffset": [
        57,
        84
      ],
      "spatialClue": {
        "anchorName": "No. 165",
        "bearing": "S",
        "distanceValue": 112,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_145_2",
      "name": "Gateway of a garden",
      "type": "gateway",
      "period": "Mughal",
      "passage": "167 yards south of No. 166, 345 yards east of No. 169, and about 30 yards north of the Delhi-Muttra Road.",
      "passageOffset": [
        687,
        792
      ],
      "spatialClue": {
        "anchorName": "Delhi-Muttra Road",
        "bearing": "N",
        "distanceValue": 30,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_145_3",
      "name": "Barah Pula",
      "type": "bridge",
      "period": "1030 A.H. (1611-2 A.D.)",
      "passage": "On the Delhi-Muttra road, between miles 4 and 5.",
      "passageOffset": [
        1151,
        1199
      ],
      "spatialClue": {
        "anchorName": "Delhi-Muttra road",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    }
  ],
  "candidates": [
    {
      "id": "c_145_2",
      "mentionId": "m_145_2",
      "centroid": [
        77.245877,
        28.590263701562176
      ],
      "uncertaintyRadiusM": 2515.4775064430187,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.48403846153846153,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-muttra-road",
        "anchorName": "Delhi-Muttra Road",
        "anchorSource": "osm:w39013511",
        "anchorCentroid": [
          77.245877,
          28.590017
        ],
        "bearingDeg": 0,
        "distanceM": 27.432,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 11.362706443018743,
          "distanceVaguenessM": 4.1148,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w403809796",
            "name": "Mosque",
            "distanceM": 213.24645899673024,
            "insideRadius": true
          },
          {
            "id": "n1754574702",
            "name": "Isa Khan's Tomb",
            "distanceM": 220.66878342679922,
            "insideRadius": true
          },
          {
            "id": "w220385655",
            "name": "Arab Sarai",
            "distanceM": 261.8446653818258,
            "insideRadius": true
          },
          {
            "id": "w403809805",
            "name": "unnamed yes (w403809805)",
            "distanceM": 280.4454878431732,
            "insideRadius": true
          },
          {
            "id": "w103505910",
            "name": "Chausath Khamba",
            "distanceM": 295.6262087520922,
            "insideRadius": true
          }
        ]
      }
    },
    {
      "id": "c_145_3",
      "mentionId": "m_145_3",
      "centroid": [
        77.245877,
        28.590017
      ],
      "uncertaintyRadiusM": 2650,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.25303846153846155,
        "parts": {
          "clueSpecificity": 0.18,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-muttra-road",
        "anchorName": "Delhi-Muttra Road",
        "anchorSource": "osm:w39013511",
        "anchorCentroid": [
          77.245877,
          28.590017
        ],
        "bearingDeg": null,
        "distanceM": null,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 0,
          "distanceVaguenessM": 150,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w403809796",
            "name": "Mosque",
            "distanceM": 240.3110210678837,
            "insideRadius": true
          },
          {
            "id": "n1754574702",
            "name": "Isa Khan's Tomb",
            "distanceM": 247.87543731514705,
            "insideRadius": true
          },
          {
            "id": "w220385655",
            "name": "Arab Sarai",
            "distanceM": 275.6516524326265,
            "insideRadius": true
          },
          {
            "id": "w163778457",
            "name": "unnamed yes (w163778457)",
            "distanceM": 299.16425699765284,
            "insideRadius": true
          },
          {
            "id": "w163778461",
            "name": "unnamed yes (w163778461)",
            "distanceM": 299.6583176833827,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
