import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 246,
  "mentions": [
    {
      "id": "m_246_1",
      "name": "Tal Katora garden",
      "type": "garden",
      "period": "Late Mughal",
      "passage": "Some 3 miles out of Shahjahanabad, due south-west of the Jami Masjid.",
      "passageOffset": [
        68,
        137
      ],
      "spatialClue": {
        "anchorName": "Jami Masjid",
        "bearing": "SW",
        "distanceValue": 3,
        "distanceUnit": "miles"
      }
    },
    {
      "id": "m_246_2",
      "name": "solitary tower",
      "type": "tower",
      "period": null,
      "passage": "At a distance of some 4.5 yards from the N.-E. corner of the Tal Katora garden there stands a solitary tower",
      "passageOffset": [
        1594,
        1702
      ],
      "spatialClue": {
        "anchorName": "Tal Katora garden",
        "bearing": "NE",
        "distanceValue": 4.5,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_246_1",
      "mentionId": "m_246_1",
      "centroid": [
        77.19849132840544,
        28.61997930323339
      ],
      "uncertaintyRadiusM": 3306.8443339712985,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.4875,
        "parts": {
          "clueSpecificity": 0.5,
          "anchorPrecision": 0.5,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "jami-masjid",
        "anchorName": "Jami Masjid",
        "anchorSource": "osm:r3926057",
        "anchorCentroid": [
          77.233467,
          28.650686
        ],
        "bearingDeg": 225,
        "distanceM": 4828.032,
        "radiusParts": {
          "anchorPrecisionM": 100,
          "bearingSpreadM": 1999.836333971299,
          "distanceVaguenessM": 1207.008,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "r5354966",
            "name": "Rashtrapati Bhavan",
            "distanceM": 631.7110997378805,
            "insideRadius": true
          },
          {
            "id": "w1218426672",
            "name": "Uprashtrapati Bhavan",
            "distanceM": 664.2694739583104,
            "insideRadius": true
          },
          {
            "id": "w359770137",
            "name": "Jaipur Column",
            "distanceM": 714.4708007079936,
            "insideRadius": true
          },
          {
            "id": "n11007213869",
            "name": "Mahatma Gandhi",
            "distanceM": 1051.7087240390526,
            "insideRadius": true
          },
          {
            "id": "n11920861769",
            "name": "Pope John-Paul II.",
            "distanceM": 1188.6832291141766,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
