import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 133,
  "mentions": [
    {
      "id": "m_133_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal period",
      "passage": "(6) Some 140 yards to the east of Mirza Muzaffar’s tomb (No. 151).",
      "passageOffset": [
        52,
        118
      ],
      "spatialClue": {
        "anchorName": "Mirza Muzaffar’s tomb",
        "bearing": "E",
        "distanceValue": 140,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_133_2",
      "name": "Unknown",
      "type": "tomb",
      "period": "974 A.H. (1566-7 A.D.)",
      "passage": "(6) Some 40 yards to the S. W. of No. 153*.",
      "passageOffset": [
        721,
        764
      ],
      "spatialClue": {
        "anchorName": "No. 153*",
        "bearing": "SW",
        "distanceValue": 40,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_133_3",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "(6) Some 200 yards to the north of No. 151.",
      "passageOffset": [
        1189,
        1232
      ],
      "spatialClue": {
        "anchorName": "No. 151",
        "bearing": "N",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_133_4",
      "name": "Unknown",
      "type": "tomb",
      "period": null,
      "passage": "(A) Some 57 yards to the north of No. 155.",
      "passageOffset": [
        1529,
        1571
      ],
      "spatialClue": {
        "anchorName": "No. 155",
        "bearing": "N",
        "distanceValue": 57,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
