import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 60,
  "mentions": [
    {
      "id": "m_60_1",
      "name": "Unknown",
      "type": "mosque",
      "period": "Afghan",
      "passage": "(b) Some 150 yards to the N. W. of No. 57.",
      "passageOffset": [
        64,
        106
      ],
      "spatialClue": {
        "anchorName": "No. 57",
        "bearing": "NW",
        "distanceValue": 150,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_60_2",
      "name": "fiijre ka Gumbad",
      "type": "tomb",
      "period": "Afghan",
      "passage": "(b) Some 150 yards to the north of No. 58.",
      "passageOffset": [
        843,
        885
      ],
      "spatialClue": {
        "anchorName": "No. 58",
        "bearing": "N",
        "distanceValue": 150,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_60_3",
      "name": "Unknown",
      "type": "mosque",
      "period": "Afghan",
      "passage": "(b) Some 180 yards to the north of No. 59.",
      "passageOffset": [
        1352,
        1394
      ],
      "spatialClue": {
        "anchorName": "No. 59",
        "bearing": "N",
        "distanceValue": 180,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
