import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 67,
  "mentions": [
    {
      "id": "m_67_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Afghan",
      "passage": "",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": null
    },
    {
      "id": "m_67_2",
      "name": "Athwans garden",
      "type": "garden",
      "period": "Afghan",
      "passage": "Some 100 yards N.-W. of No. 75.",
      "passageOffset": [
        480,
        511
      ],
      "spatialClue": {
        "anchorName": "No. 75",
        "bearing": "NW",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_67_3",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "Some 18 yards to the east of No. 76.",
      "passageOffset": [
        835,
        871
      ],
      "spatialClue": {
        "anchorName": "No. 76",
        "bearing": "E",
        "distanceValue": 18,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_67_4",
      "name": "Tomb (unknown)",
      "type": "tomb",
      "period": "Afghan period",
      "passage": "Some 88 yards to the north of No. 77^",
      "passageOffset": [
        1162,
        1199
      ],
      "spatialClue": {
        "anchorName": "No. 77",
        "bearing": "N",
        "distanceValue": 88,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
