import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 32,
  "mentions": [
    {
      "id": "m_32_1",
      "name": "Delhi Observ.atory or Jantar Mantar",
      "type": "other",
      "period": null,
      "passage": "The observatory is 3 miles 3| furlongs almost due south from the Pir Gliaib, the Trigonometrical Survey point on the Ridge, near to Hindu Rao’s House.",
      "passageOffset": [
        758,
        908
      ],
      "spatialClue": {
        "anchorName": "Pir Gliaib",
        "bearing": "S",
        "distanceValue": 3.375,
        "distanceUnit": "miles"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_32_1",
      "mentionId": "m_32_1",
      "centroid": [
        77.213211,
        28.627448090688972
      ],
      "uncertaintyRadiusM": 3647.699875717711,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.5517857142857143,
        "parts": {
          "clueSpecificity": 0.5,
          "anchorPrecision": 0.7142857142857143,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "pir-ghaib",
        "anchorName": "Pir Ghaib",
        "anchorSource": "osm:n2940614717",
        "anchorCentroid": [
          77.213211,
          28.676295
        ],
        "bearingDeg": 180,
        "distanceM": 5431.536,
        "radiusParts": {
          "anchorPrecisionM": 40,
          "bearingSpreadM": 2249.815875717711,
          "distanceVaguenessM": 1357.884,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w1137558570",
            "name": "Misra Yantra",
            "distanceM": 309.1966274054299,
            "insideRadius": true
          },
          {
            "id": "w1137558567",
            "name": "Jai Prakash Yantra",
            "distanceM": 332.1874146307982,
            "insideRadius": true
          },
          {
            "id": "w223456559",
            "name": "Jantar Mantar",
            "distanceM": 332.69031222338157,
            "insideRadius": true
          },
          {
            "id": "w223456540",
            "name": "Samrat Yantra",
            "distanceM": 334.3708656443225,
            "insideRadius": true
          },
          {
            "id": "w500413797",
            "name": "Ram Yantra",
            "distanceM": 340.7833547780326,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
