import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 130,
  "mentions": [
    {
      "id": "m_130_1",
      "name": "Unknown",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "On Delhi-Mutra road, at the junction of the road leading towards the tomb of Safdar Jang.",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "Delhi-Mutra road",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_130_2",
      "name": "Unknown",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 100 yards to the east of No. 142.",
      "passageOffset": [
        546,
        584
      ],
      "spatialClue": {
        "anchorName": "No. 142",
        "bearing": "E",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_130_3",
      "name": "Sundarwala Burj",
      "type": "tomb",
      "period": "Mughal",
      "passage": "Some 270 yards from the N. E. corner of Buhalima’s Garden (No. 178), towards the north.",
      "passageOffset": [
        849,
        936
      ],
      "spatialClue": {
        "anchorName": "Buhalima’s Garden",
        "bearing": "N",
        "distanceValue": 270,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_130_4",
      "name": "Sundarwala Mahal",
      "type": "tomb",
      "period": null,
      "passage": "Some 270 yards from the N. E. comer of Buhalima’s Garden towards the north, and some 110 yards to the east of No. 148.",
      "passageOffset": [
        1401,
        1519
      ],
      "spatialClue": {
        "anchorName": "Buhalima’s Garden",
        "bearing": "N",
        "distanceValue": 270,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
