import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 241,
  "mentions": [
    {
      "id": "m_241_1",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "iVfghan",
      "passage": "Some 10 yards from No. 31S to the south.",
      "passageOffset": [
        419,
        459
      ],
      "spatialClue": {
        "anchorName": "No. 31S",
        "bearing": "S",
        "distanceValue": 10,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_241_2",
      "name": "Munda Gumbad (roofless dome)",
      "type": "tomb",
      "period": "Afghan",
      "passage": "Some 400 yards from No. 312 towards east.",
      "passageOffset": [
        1034,
        1075
      ],
      "spatialClue": {
        "anchorName": "No. 312",
        "bearing": "E",
        "distanceValue": 400,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_241_3",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": null,
      "passage": "Some 150 yards from No. 312 towards south.",
      "passageOffset": [
        1976,
        2018
      ],
      "spatialClue": {
        "anchorName": "No. 312",
        "bearing": "S",
        "distanceValue": 150,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
