import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 129,
  "mentions": [
    {
      "id": "m_129_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Afghan",
      "passage": "Some 60 yards east of the Delhi-Muttra road, between the 2nd and 3rd furlongs past the 3rd milestone.",
      "passageOffset": [
        67,
        168
      ],
      "spatialClue": {
        "anchorName": "Delhi-Muttra road",
        "bearing": "E",
        "distanceValue": 60,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_129_2",
      "name": "Unknown",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 25 yards to the north of No. 142.",
      "passageOffset": [
        382,
        420
      ],
      "spatialClue": {
        "anchorName": "No. 142",
        "bearing": "N",
        "distanceValue": 25,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_129_3",
      "name": "Unknown",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 40 yards to the north of No. 142, and 15 yards to the west of No. 143.",
      "passageOffset": [
        630,
        705
      ],
      "spatialClue": {
        "anchorName": "No. 142",
        "bearing": "N",
        "distanceValue": 40,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_129_4",
      "name": "Unknown",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 20 yards to the north of No. 144.",
      "passageOffset": [
        1091,
        1129
      ],
      "spatialClue": {
        "anchorName": "No. 144",
        "bearing": "N",
        "distanceValue": 20,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_129_1",
      "mentionId": "m_129_1",
      "centroid": [
        77.24643892008096,
        28.59001699884218
      ],
      "uncertaintyRadiusM": 2530.955012886038,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.48403846153846153,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-muttra-road",
        "anchorName": "Delhi-Muttra Road",
        "anchorSource": "osm:w39013511",
        "anchorCentroid": [
          77.245877,
          28.590017
        ],
        "bearingDeg": 90,
        "distanceM": 54.864,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 22.725412886037486,
          "distanceVaguenessM": 8.2296,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w220385655",
            "name": "Arab Sarai",
            "distanceM": 231.39884772423736,
            "insideRadius": true
          },
          {
            "id": "n1754574702",
            "name": "Isa Khan's Tomb",
            "distanceM": 247.32519309132456,
            "insideRadius": true
          },
          {
            "id": "w403809796",
            "name": "Mosque",
            "distanceM": 254.58043807578866,
            "insideRadius": true
          },
          {
            "id": "w163778457",
            "name": "unnamed yes (w163778457)",
            "distanceM": 264.14938307799713,
            "insideRadius": true
          },
          {
            "id": "w163778461",
            "name": "unnamed yes (w163778461)",
            "distanceM": 264.56103541104994,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
