import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 314,
  "mentions": [
    {
      "id": "m_314_1",
      "name": "miniature battery No. Ill",
      "type": "other",
      "period": null,
      "passage": "lies some 75 yards to the south of the mosque",
      "passageOffset": [
        492,
        537
      ],
      "spatialClue": {
        "anchorName": "mosque",
        "bearing": "S",
        "distanceValue": 75,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_314_2",
      "name": "miniature battery No. TV",
      "type": "other",
      "period": null,
      "passage": "lies some 100 yards to N. W. of the gateway (No. 412)",
      "passageOffset": [
        835,
        888
      ],
      "spatialClue": {
        "anchorName": "gateway (No. 412)",
        "bearing": "NW",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_314_3",
      "name": "Gateway",
      "type": "gateway",
      "period": "1748 A.D. (Asar)",
      "passage": "In the Gardens, about 300 yards to the west of No. 411.",
      "passageOffset": [
        1352,
        1407
      ],
      "spatialClue": {
        "anchorName": "No. 411",
        "bearing": "W",
        "distanceValue": 300,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
