import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 32,
  "mentions": [
    {
      "id": "m_32_1",
      "name": "Delhi Observ.atory or Jant.^r Mantar",
      "type": "other",
      "period": null,
      "passage": "The observatory is 3 miles 3| furlongs almost due south from the Pir\nGliaib, the Trigonometrical Survey point on the Ridge, near to Hindu Rao’s\nHouse.",
      "passageOffset": [
        758,
        908
      ],
      "spatialClue": {
        "anchorName": "Pir Gliaib",
        "bearing": "S",
        "distanceValue": 3.375,
        "distanceUnit": "miles"
      }
    },
    {
      "id": "m_32_2",
      "name": "Samrat Yantra",
      "type": "other",
      "period": null,
      "passage": "{j) The Samrat Yantra (\" Supreme instrument ”) a huge equinoctial\ndial.",
      "passageOffset": [
        1395,
        1466
      ],
      "spatialClue": null
    },
    {
      "id": "m_32_3",
      "name": "Jai Prakas",
      "type": "other",
      "period": null,
      "passage": "The Jai Prakas. consisting of two hemispherical structures, just to the south of the Samrat Yantra.",
      "passageOffset": [
        1473,
        1572
      ],
      "spatialClue": {
        "anchorName": "Samrat Yantra",
        "bearing": "S",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_32_4",
      "name": "Ram Yantra",
      "type": "other",
      "period": null,
      "passage": "The Ram Yantra, consisting of two circular buildings to the south of the Jai Prakas.",
      "passageOffset": [
        1577,
        1661
      ],
      "spatialClue": {
        "anchorName": "Jai Prakas",
        "bearing": "S",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_32_5",
      "name": "Misra Yantra",
      "type": "other",
      "period": null,
      "passage": "The Misra Yantra ('^ mixed instrument ”), north-west of the Samrat Yantra.",
      "passageOffset": [
        1667,
        1741
      ],
      "spatialClue": {
        "anchorName": "Samrat Yantra",
        "bearing": "NW",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_32_6",
      "name": "Two pillars",
      "type": "other",
      "period": null,
      "passage": "Two pillars south-west of the Misra Yantra.",
      "passageOffset": [
        1746,
        1789
      ],
      "spatialClue": {
        "anchorName": "Misra Yantra",
        "bearing": "SW",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_32_7",
      "name": "Measuring platform",
      "type": "other",
      "period": null,
      "passage": "A measuring platform, just south of the Misra Yantra.",
      "passageOffset": [
        1794,
        1847
      ],
      "spatialClue": {
        "anchorName": "Misra Yantra",
        "bearing": "S",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_32_8",
      "name": "Samb.\\t Y.vntra",
      "type": "other",
      "period": null,
      "passage": "The Samb.\\t Y.vntra is the central building of the observatory.",
      "passageOffset": [
        1848,
        1911
      ],
      "spatialClue": null
    }
  ],
  "candidates": [
    {
      "id": "c_32_1",
      "mentionId": "m_32_1",
      "centroid": [
        77.213211,
        28.627448090688972
      ],
      "uncertaintyRadiusM": 3647.699875717711,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.5517857142857143,
        "parts": {
          "clueSpecificity": 0.5,
          "anchorPrecision": 0.7142857142857143,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "pir-ghaib",
        "anchorName": "Pir Ghaib",
        "anchorSource": "osm:n2940614717",
        "anchorCentroid": [
          77.213211,
          28.676295
        ],
        "bearingDeg": 180,
        "distanceM": 5431.536,
        "radiusParts": {
          "anchorPrecisionM": 40,
          "bearingSpreadM": 2249.815875717711,
          "distanceVaguenessM": 1357.884,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w1137558570",
            "name": "Misra Yantra",
            "distanceM": 309.1966274054299,
            "insideRadius": true
          },
          {
            "id": "w1137558567",
            "name": "Jai Prakash Yantra",
            "distanceM": 332.1874146307982,
            "insideRadius": true
          },
          {
            "id": "w223456559",
            "name": "Jantar Mantar",
            "distanceM": 332.69031222338157,
            "insideRadius": true
          },
          {
            "id": "w223456540",
            "name": "Samrat Yantra",
            "distanceM": 334.3708656443225,
            "insideRadius": true
          },
          {
            "id": "w500413797",
            "name": "Ram Yantra",
            "distanceM": 340.7833547780326,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
