import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 236,
  "mentions": [
    {
      "id": "m_236_1",
      "name": "Debi Singh",
      "type": "tomb",
      "period": "Afghan",
      "passage": "",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": null
    },
    {
      "id": "m_236_2",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Afghan",
      "passage": "About 10 yards towards west of No. 305.",
      "passageOffset": [
        483,
        522
      ],
      "spatialClue": {
        "anchorName": "No. 305",
        "bearing": "W",
        "distanceValue": 10,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_236_3",
      "name": "unknown",
      "type": "tomb",
      "period": "Afghan",
      "passage": "Some 15 yards to S.-E. of No. 306.",
      "passageOffset": [
        1036,
        1070
      ],
      "spatialClue": {
        "anchorName": "No. 306",
        "bearing": "SE",
        "distanceValue": 15,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_236_4",
      "name": "Tomb of Musa Khan",
      "type": "tomb",
      "period": null,
      "passage": "Some 200 yards to south of No. 307.",
      "passageOffset": [
        1529,
        1564
      ],
      "spatialClue": {
        "anchorName": "No. 307",
        "bearing": "S",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
