import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 292,
  "mentions": [
    {
      "id": "m_292_1",
      "name": "MALAKPUR CHHAWNI",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "(b) About 300 yards N. W. of Government House.",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "Government House",
        "bearing": "NW",
        "distanceValue": 300,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_292_2",
      "name": "Kos Minar",
      "type": "tower",
      "period": "Jahangir’s time",
      "passage": "(b) About 3 furlongs to the north of No. 393, on the Delhi-Karnal road (3 miles 4 furlongs from Delhi).",
      "passageOffset": [
        986,
        1089
      ],
      "spatialClue": {
        "anchorName": "Delhi-Karnal road",
        "bearing": "N",
        "distanceValue": 3,
        "distanceUnit": "furlongs"
      }
    },
    {
      "id": "m_292_3",
      "name": "Unknown",
      "type": "tomb",
      "period": "Late Mughal",
      "passage": "(b) About 30 yards to N. E. of No. 396.",
      "passageOffset": [
        1316,
        1355
      ],
      "spatialClue": {
        "anchorName": "No. 396",
        "bearing": "NE",
        "distanceValue": 30,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_292_1",
      "mentionId": "m_292_1",
      "centroid": [
        77.21206440489733,
        28.690704428942652
      ],
      "uncertaintyRadiusM": 404.7750644301874,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.5582142857142857,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.2857142857142857,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "government-house",
        "anchorName": "Government House",
        "anchorSource": "osm:r18941467",
        "anchorCentroid": [
          77.214053,
          28.68896
        ],
        "bearingDeg": 315,
        "distanceM": 274.32,
        "radiusParts": {
          "anchorPrecisionM": 250,
          "bearingSpreadM": 113.62706443018743,
          "distanceVaguenessM": 41.147999999999996,
          "floorTopUpM": 0
        },
        "baselineVerdict": "representation_gap",
        "baselineChecked": [
          {
            "id": "n12696121640",
            "name": "Allnutt's Celtic Cross",
            "distanceM": 457.78895818541815,
            "insideRadius": false
          },
          {
            "id": "n12806176744",
            "name": "Foundation Stone",
            "distanceM": 573.7603069515355,
            "insideRadius": false
          },
          {
            "id": "w1487074888",
            "name": "unnamed building (w1487074888)",
            "distanceM": 635.06937882911,
            "insideRadius": false
          },
          {
            "id": "w1410331570",
            "name": "Flagstaff Tower",
            "distanceM": 667.8277971266723,
            "insideRadius": false
          },
          {
            "id": "n13594703577",
            "name": "unnamed no (n13594703577)",
            "distanceM": 1059.9762863007034,
            "insideRadius": false
          }
        ]
      }
    },
    {
      "id": "c_292_2",
      "mentionId": "m_292_2",
      "centroid": [
        77.197412,
        28.688234434367892
      ],
      "uncertaintyRadiusM": 2900.8555417464127,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.37903846153846155,
        "parts": {
          "clueSpecificity": 0.6,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-karnal-road",
        "anchorName": "Delhi-Karnal Road",
        "anchorSource": "osm:w1486834964",
        "anchorCentroid": [
          77.197412,
          28.682807
        ],
        "bearingDeg": 0,
        "distanceM": 603.504,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 249.97954174641237,
          "distanceVaguenessM": 150.876,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w1537377155",
            "name": "Tripolia Gate (North)",
            "distanceM": 329.2944537838447,
            "insideRadius": true
          },
          {
            "id": "w351621253",
            "name": "Tripolia Gate (South)",
            "distanceM": 357.80256943900156,
            "insideRadius": true
          },
          {
            "id": "n2940758785",
            "name": "Shah Wajid Mosque",
            "distanceM": 1393.6600474287745,
            "insideRadius": true
          },
          {
            "id": "n12806176744",
            "name": "Foundation Stone",
            "distanceM": 1416.1189140242002,
            "insideRadius": true
          },
          {
            "id": "n12696121640",
            "name": "Allnutt's Celtic Cross",
            "distanceM": 1446.9728103721907,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
