import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 246,
  "mentions": [
    {
      "id": "m_246_1",
      "name": "Tal Katora garden",
      "type": "garden",
      "period": "Late Mughal",
      "passage": "(b) Some 3 miles out of Shahjahanabad, due south-west of the Jami Masjid.",
      "passageOffset": [
        64,
        137
      ],
      "spatialClue": {
        "anchorName": "Shahjahanabad",
        "bearing": "SW",
        "distanceValue": 3,
        "distanceUnit": "miles"
      }
    },
    {
      "id": "m_246_2",
      "name": "gateway",
      "type": "gateway",
      "period": null,
      "passage": "Opposite the baradari, towards the north, stands a gateway which was probably an entrance to the garden.",
      "passageOffset": [
        693,
        797
      ],
      "spatialClue": {
        "anchorName": "baradari",
        "bearing": "opposite",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_246_3",
      "name": "baradari",
      "type": "pavilion",
      "period": null,
      "passage": "In the centre of the garden there appears to have been a baradari which is now no better than a heap of ruins.",
      "passageOffset": [
        582,
        692
      ],
      "spatialClue": {
        "anchorName": "centre of the garden",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_246_4",
      "name": "solitary tower",
      "type": "tower",
      "period": null,
      "passage": "At a distance of some 4.5 yards from the N.-E. corner of the Tal Katora garden there stands a solitary tower",
      "passageOffset": [
        1594,
        1702
      ],
      "spatialClue": {
        "anchorName": "N.-E. corner of the Tal Katora garden",
        "bearing": "adjacent",
        "distanceValue": 4.5,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_246_5",
      "name": "double-storeyed octagonal pavilions",
      "type": "pavilion",
      "period": null,
      "passage": "flanked at each end by double-storeyed octagonal pavilions surmounted by domes.",
      "passageOffset": [
        908,
        987
      ],
      "spatialClue": {
        "anchorName": "terrace",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_246_6",
      "name": "high terrace",
      "type": "other",
      "period": null,
      "passage": "At the northern end of the garden overlooking the tank there is a high terrace measuring 631' 6\" by 62' 6\"",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "northern end of the garden",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_246_7",
      "name": "gateway",
      "type": "gateway",
      "period": null,
      "passage": "A gateway which seems to have been an entrance to the platform is also to be found just by the side of these towers.",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "side of these towers",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    }
  ],
  "candidates": [
    {
      "id": "c_246_1",
      "mentionId": "m_246_1",
      "centroid": [
        77.19952455690749,
        28.619293303361193
      ],
      "uncertaintyRadiusM": 4606.8443339712985,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.3575,
        "parts": {
          "clueSpecificity": 0.5,
          "anchorPrecision": 0.06666666666666667,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "shahjahanabad",
        "anchorName": "Shahjahanabad",
        "anchorSource": "approximate",
        "anchorCentroid": [
          77.2345,
          28.65
        ],
        "bearingDeg": 225,
        "distanceM": 4828.032,
        "radiusParts": {
          "anchorPrecisionM": 1400,
          "bearingSpreadM": 1999.836333971299,
          "distanceVaguenessM": 1207.008,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w1218426672",
            "name": "Uprashtrapati Bhavan",
            "distanceM": 537.8736656867967,
            "insideRadius": true
          },
          {
            "id": "r5354966",
            "name": "Rashtrapati Bhavan",
            "distanceM": 547.2693220984008,
            "insideRadius": true
          },
          {
            "id": "w359770137",
            "name": "Jaipur Column",
            "distanceM": 603.3857206645209,
            "insideRadius": true
          },
          {
            "id": "n11007213869",
            "name": "Mahatma Gandhi",
            "distanceM": 938.0034259643917,
            "insideRadius": true
          },
          {
            "id": "n11920861769",
            "name": "Pope John-Paul II.",
            "distanceM": 1184.2110144487553,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
