import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 58,
  "mentions": [
    {
      "id": "m_58_1",
      "name": "Unknown",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "Some 170 yards to the east of No. 51.",
      "passageOffset": [
        57,
        94
      ],
      "spatialClue": {
        "anchorName": "No. 51",
        "bearing": "E",
        "distanceValue": 170,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_58_2",
      "name": "Unknown",
      "type": "gateway",
      "period": "Unknown",
      "passage": "Some 400 yards to the north of No. 51.",
      "passageOffset": [
        387,
        425
      ],
      "spatialClue": {
        "anchorName": "No. 51",
        "bearing": "N",
        "distanceValue": 400,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_58_3",
      "name": "Unknown",
      "type": "other",
      "period": "Unknown",
      "passage": "Some 100 yards to the west of No. 53.",
      "passageOffset": [
        740,
        777
      ],
      "spatialClue": {
        "anchorName": "No. 53",
        "bearing": "W",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_58_4",
      "name": "Unknown",
      "type": "tomb",
      "period": "Afghan",
      "passage": "Some 50 yards to N. W. of the village,",
      "passageOffset": [
        1182,
        1220
      ],
      "spatialClue": {
        "anchorName": "the village",
        "bearing": "NW",
        "distanceValue": 50,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
