import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 73,
  "mentions": [
    {
      "id": "m_73_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Sher Shah’s period",
      "passage": " Some 70 yards to the west of Delhi-Muttra Road opposite the Talaqi gate of the old fort.",
      "passageOffset": [
        594,
        682
      ],
      "spatialClue": {
        "anchorName": "Delhi-Muttra Road",
        "bearing": "W",
        "distanceValue": 70,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_73_2",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": " Some 200 yards to the west of Delhi-Muttra Road at the 5th furlong past the 1st mile-stone from Delhi.",
      "passageOffset": [
        1059,
        1161
      ],
      "spatialClue": {
        "anchorName": "Delhi-Muttra Road",
        "bearing": "W",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_73_3",
      "name": "Nili Chattri or the tomb of Naubat Khan (distinguished from the Nila Gumbad near Humayun’s tomb. See No. 164; and the Nili Chattri near Salimgarh, see No. 411)",
      "type": "tomb",
      "period": null,
      "passage": " At the third mile-stone, and some 25 yards east of the Delhi-Muttra Road,",
      "passageOffset": [
        1773,
        1847
      ],
      "spatialClue": {
        "anchorName": "Delhi-Muttra Road",
        "bearing": "E",
        "distanceValue": 25,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_73_1",
      "mentionId": "m_73_1",
      "centroid": [
        77.24522142657221,
        28.590016998424076
      ],
      "uncertaintyRadiusM": 2536.1141817003772,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.48403846153846153,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-muttra-road",
        "anchorName": "Delhi-Muttra Road",
        "anchorSource": "osm:w39013511",
        "anchorCentroid": [
          77.245877,
          28.590017
        ],
        "bearingDeg": 270,
        "distanceM": 64.008,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 26.512981700377065,
          "distanceVaguenessM": 9.601199999999999,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w403809796",
            "name": "Mosque",
            "distanceM": 238.99657831801355,
            "insideRadius": true
          },
          {
            "id": "w103505910",
            "name": "Chausath Khamba",
            "distanceM": 249.99035632298072,
            "insideRadius": true
          },
          {
            "id": "n1754574702",
            "name": "Isa Khan's Tomb",
            "distanceM": 263.37973769924145,
            "insideRadius": true
          },
          {
            "id": "n1195165037",
            "name": "Mirza Ghalib's Tomb",
            "distanceM": 266.70006821124366,
            "insideRadius": true
          },
          {
            "id": "w403809805",
            "name": "unnamed yes (w403809805)",
            "distanceM": 318.8419204828144,
            "insideRadius": true
          }
        ]
      }
    },
    {
      "id": "c_73_2",
      "mentionId": "m_73_2",
      "centroid": [
        77.2440039330636,
        28.590016987135332
      ],
      "uncertaintyRadiusM": 2603.1833762867914,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.48403846153846153,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-muttra-road",
        "anchorName": "Delhi-Muttra Road",
        "anchorSource": "osm:w39013511",
        "anchorCentroid": [
          77.245877,
          28.590017
        ],
        "bearingDeg": 270,
        "distanceM": 182.88,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 75.75137628679161,
          "distanceVaguenessM": 27.432,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w103505910",
            "name": "Chausath Khamba",
            "distanceM": 161.32941144181547,
            "insideRadius": true
          },
          {
            "id": "n1195165037",
            "name": "Mirza Ghalib's Tomb",
            "distanceM": 184.364419366986,
            "insideRadius": true
          },
          {
            "id": "n7040397189",
            "name": "Ataga Khan's Tomb",
            "distanceM": 243.55481563561585,
            "insideRadius": true
          },
          {
            "id": "w103505909",
            "name": "Nizamuddin Dargah",
            "distanceM": 249.2906299222122,
            "insideRadius": true
          },
          {
            "id": "w1361098049",
            "name": "Nizamuddin Dargah Complex",
            "distanceM": 257.10189624782186,
            "insideRadius": true
          }
        ]
      }
    },
    {
      "id": "c_73_3",
      "mentionId": "m_73_3",
      "centroid": [
        77.24611113336707,
        28.59001699979899
      ],
      "uncertaintyRadiusM": 2512.897922035849,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.48403846153846153,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-muttra-road",
        "anchorName": "Delhi-Muttra Road",
        "anchorSource": "osm:w39013511",
        "anchorCentroid": [
          77.245877,
          28.590017
        ],
        "bearingDeg": 90,
        "distanceM": 22.86,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 9.468922035848951,
          "distanceVaguenessM": 3.429,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w403809796",
            "name": "Mosque",
            "distanceM": 244.86771393015482,
            "insideRadius": true
          },
          {
            "id": "n1754574702",
            "name": "Isa Khan's Tomb",
            "distanceM": 246.16475603768254,
            "insideRadius": true
          },
          {
            "id": "w220385655",
            "name": "Arab Sarai",
            "distanceM": 256.7155739307245,
            "insideRadius": true
          },
          {
            "id": "w163778457",
            "name": "unnamed yes (w163778457)",
            "distanceM": 283.8118382368291,
            "insideRadius": true
          },
          {
            "id": "w163778461",
            "name": "unnamed yes (w163778461)",
            "distanceM": 284.2752658823777,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
