import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 61,
  "mentions": [
    {
      "id": "m_61_1",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Afghan",
      "passage": "Some 200 yards to the west of No. 60.",
      "passageOffset": [
        313,
        350
      ],
      "spatialClue": {
        "anchorName": "No. 60",
        "bearing": "W",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_61_2",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 20 yards to the west of No. 63.",
      "passageOffset": [
        726,
        762
      ],
      "spatialClue": {
        "anchorName": "No. 63",
        "bearing": "W",
        "distanceValue": 20,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_61_3",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "Some 400 yards to the S. W. of Khairul Manazil (No. 83).",
      "passageOffset": [
        1024,
        1080
      ],
      "spatialClue": {
        "anchorName": "Khairul Manazil",
        "bearing": "SW",
        "distanceValue": 400,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_61_4",
      "name": "Mir Taqi’s tomb",
      "type": "tomb",
      "period": null,
      "passage": "Some 270 yards to the south of No. 63.",
      "passageOffset": [
        1306,
        1344
      ],
      "spatialClue": {
        "anchorName": "No. 63",
        "bearing": "S",
        "distanceValue": 270,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_61_3",
      "mentionId": "m_61_3",
      "centroid": [
        77.23690570146383,
        28.60516704961927
      ],
      "uncertaintyRadiusM": 246.36675257358323,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.6867857142857142,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.7142857142857143,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "khair-ul-manazil",
        "anchorName": "Khair-ul-Manazil",
        "anchorSource": "osm:n7043400785",
        "anchorCentroid": [
          77.239555,
          28.607493
        ],
        "bearingDeg": 225,
        "distanceM": 365.76,
        "radiusParts": {
          "anchorPrecisionM": 40,
          "bearingSpreadM": 151.50275257358322,
          "distanceVaguenessM": 54.864,
          "floorTopUpM": 0
        },
        "baselineVerdict": "representation_gap",
        "baselineChecked": [
          {
            "id": "n7043400785",
            "name": "Khair-U’l-Manazil Masjid",
            "distanceM": 365.81906196513546,
            "insideRadius": false
          },
          {
            "id": "n11816164804",
            "name": "unnamed aircraft (n11816164804)",
            "distanceM": 366.3396863008503,
            "insideRadius": false
          },
          {
            "id": "w973075865",
            "name": "unnamed citywalls (w973075865)",
            "distanceM": 441.5860111330963,
            "insideRadius": false
          },
          {
            "id": "w973075861",
            "name": "Sher Shah Suri Gate",
            "distanceM": 443.31509250255664,
            "insideRadius": false
          },
          {
            "id": "n11816141464",
            "name": "unnamed aircraft (n11816141464)",
            "distanceM": 460.37921105290496,
            "insideRadius": false
          }
        ]
      }
    }
  ]
};

export default page;
