import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 196,
  "mentions": [
    {
      "id": "m_196_1",
      "name": "Khanqah of Shah Rahim Bakhsh",
      "type": "other",
      "period": "1250 A.H. (1834 A.D.)",
      "passage": "Kotla Nizamuddin, some 26 paces to N. E, of No. 239.",
      "passageOffset": [
        71,
        123
      ],
      "spatialClue": {
        "anchorName": "No. 239",
        "bearing": "NE",
        "distanceValue": 26,
        "distanceUnit": "paces"
      }
    },
    {
      "id": "m_196_2",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Originally Pathan period perhaps, but restored features are all Mughal.",
      "passage": "Village of Nizamuddin, some 9 paces to the north of the gateway of the inner Kot (No. 241).",
      "passageOffset": [
        865,
        956
      ],
      "spatialClue": {
        "anchorName": "gateway",
        "bearing": "N",
        "distanceValue": 9,
        "distanceUnit": "paces"
      }
    },
    {
      "id": "m_196_3",
      "name": "Kali Masjid",
      "type": "mosque",
      "period": "772 A.H. (1370-1 A.D.)",
      "passage": "Village of Nizamuddin, some 16 yards to the east of inner Kot (No. 241).",
      "passageOffset": [
        1451,
        1523
      ],
      "spatialClue": {
        "anchorName": "inner Kot",
        "bearing": "E",
        "distanceValue": 16,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
