import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 75,
  "mentions": [
    {
      "id": "m_75_1",
      "name": "Unknown",
      "type": "tomb",
      "period": null,
      "passage": "",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": null
    },
    {
      "id": "m_75_2",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Mughal",
      "passage": "On the road from Humayun’s tomb to Safdar Jang, towards south, and some 30 yards to the north of No. 90.",
      "passageOffset": [
        479,
        583
      ],
      "spatialClue": {
        "anchorName": "Humayun’s tomb",
        "bearing": "S",
        "distanceValue": 30,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_75_3",
      "name": "A domed building (probably an entrance)",
      "type": "gateway",
      "period": "Mughal",
      "passage": "On the road from Humayun’s tomb to Safdar Jang, towards south, ajid some 60 yards to the west of No. 91.",
      "passageOffset": [
        861,
        965
      ],
      "spatialClue": {
        "anchorName": "Humayun’s tomb",
        "bearing": "S",
        "distanceValue": 60,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_75_4",
      "name": "Gol Gumbad (round dome)",
      "type": "tomb",
      "period": "Afghan",
      "passage": "On the road from Humayun’s tomb to Safdar Jang, at the railway crossing.",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "Humayun’s tomb",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    }
  ],
  "candidates": [
    {
      "id": "c_75_2",
      "mentionId": "m_75_2",
      "centroid": [
        77.250646,
        28.59303929843782
      ],
      "uncertaintyRadiusM": 135.47750644301874,
      "status": "matched_existing",
      "matchedBaselineFeature": {
        "id": "w220385654",
        "name": "Humayun's Tomb",
        "distanceM": 27.454282417646876
      },
      "confidence": {
        "total": 0.6911650160510493,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.45454545454545453,
          "sourceReliability": 0.9,
          "modernEvidence": 0.8986758645827526,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "humayuns-tomb",
        "anchorName": "Humayun's Tomb",
        "anchorSource": "osm:w220385654",
        "anchorCentroid": [
          77.250646,
          28.593286
        ],
        "bearingDeg": 180,
        "distanceM": 27.432,
        "radiusParts": {
          "anchorPrecisionM": 120,
          "bearingSpreadM": 11.362706443018743,
          "distanceVaguenessM": 4.1148,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w220385654",
            "name": "Humayun's Tomb",
            "distanceM": 27.454282417646876,
            "insideRadius": true
          },
          {
            "id": "w220385656",
            "name": "Barber's Tomb",
            "distanceM": 149.39124014838714,
            "insideRadius": false
          },
          {
            "id": "w403809791",
            "name": "Royal Gateway",
            "distanceM": 162.62078700739133,
            "insideRadius": false
          },
          {
            "id": "w432131635",
            "name": "unnamed tomb (w432131635)",
            "distanceM": 172.59434372920134,
            "insideRadius": false
          },
          {
            "id": "w432131641",
            "name": "unnamed tomb (w432131641)",
            "distanceM": 173.89534650669296,
            "insideRadius": false
          }
        ]
      }
    },
    {
      "id": "c_75_3",
      "mentionId": "m_75_3",
      "centroid": [
        77.250646,
        28.592792596875647
      ],
      "uncertaintyRadiusM": 150.95501288603748,
      "status": "matched_existing",
      "matchedBaselineFeature": {
        "id": "w220385654",
        "name": "Humayun's Tomb",
        "distanceM": 54.88626072549964
      },
      "confidence": {
        "total": 0.6790941242373967,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.45454545454545453,
          "sourceReliability": 0.9,
          "modernEvidence": 0.8182032524917352,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "humayuns-tomb",
        "anchorName": "Humayun's Tomb",
        "anchorSource": "osm:w220385654",
        "anchorCentroid": [
          77.250646,
          28.593286
        ],
        "bearingDeg": 180,
        "distanceM": 54.864,
        "radiusParts": {
          "anchorPrecisionM": 120,
          "bearingSpreadM": 22.725412886037486,
          "distanceVaguenessM": 8.2296,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w220385654",
            "name": "Humayun's Tomb",
            "distanceM": 54.88626072549964,
            "insideRadius": true
          },
          {
            "id": "w403809791",
            "name": "Royal Gateway",
            "distanceM": 135.27638246372348,
            "insideRadius": true
          },
          {
            "id": "w220385656",
            "name": "Barber's Tomb",
            "distanceM": 135.49916343756274,
            "insideRadius": true
          },
          {
            "id": "w163778032",
            "name": "Bu Halima Gate",
            "distanceM": 184.5404986000904,
            "insideRadius": false
          },
          {
            "id": "n7040083886",
            "name": "East Pavilion",
            "distanceM": 193.61223161614046,
            "insideRadius": false
          }
        ]
      }
    },
    {
      "id": "c_75_4",
      "mentionId": "m_75_4",
      "centroid": [
        77.250646,
        28.593286
      ],
      "uncertaintyRadiusM": 270,
      "status": "matched_existing",
      "matchedBaselineFeature": {
        "id": "w220385654",
        "name": "Humayun's Tomb",
        "distanceM": 0.0536437784595541
      },
      "confidence": {
        "total": 0.47534873531406424,
        "parts": {
          "clueSpecificity": 0.18,
          "anchorPrecision": 0.45454545454545453,
          "sourceReliability": 0.9,
          "modernEvidence": 0.9999006596695194,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "humayuns-tomb",
        "anchorName": "Humayun's Tomb",
        "anchorSource": "osm:w220385654",
        "anchorCentroid": [
          77.250646,
          28.593286
        ],
        "bearingDeg": null,
        "distanceM": null,
        "radiusParts": {
          "anchorPrecisionM": 120,
          "bearingSpreadM": 0,
          "distanceVaguenessM": 150,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w220385654",
            "name": "Humayun's Tomb",
            "distanceM": 0.0536437784595541,
            "insideRadius": true
          },
          {
            "id": "w432131635",
            "name": "unnamed tomb (w432131635)",
            "distanceM": 152.3088448168304,
            "insideRadius": true
          },
          {
            "id": "w432131641",
            "name": "unnamed tomb (w432131641)",
            "distanceM": 153.78750717128045,
            "insideRadius": true
          },
          {
            "id": "w432131639",
            "name": "unnamed tomb (w432131639)",
            "distanceM": 155.3320142540291,
            "insideRadius": true
          },
          {
            "id": "w432131640",
            "name": "unnamed tomb (w432131640)",
            "distanceM": 159.0348558992317,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
