import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 64,
  "mentions": [
    {
      "id": "m_64_1",
      "name": "Tomb of Sajyid Abid",
      "type": "tomb",
      "period": "About 1036 A.H. (1626-27 A.D.)",
      "passage": "Some 90 yards to the south of No. 67.",
      "passageOffset": [
        1493,
        1530
      ],
      "spatialClue": {
        "anchorName": "No. 67",
        "bearing": "S",
        "distanceValue": 90,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_64_2",
      "name": "Unknown",
      "type": "tomb",
      "period": null,
      "passage": "Some 150 yards to the S. W. of No. 68.",
      "passageOffset": [
        2099,
        2137
      ],
      "spatialClue": {
        "anchorName": "No. 68",
        "bearing": "SW",
        "distanceValue": 150,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
