import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 28,
  "mentions": [
    {
      "id": "m_28_1",
      "name": "Nasyan",
      "type": "temple",
      "period": "Late Mughal",
      "passage": "Some 200 yards from No. 17 towards west.",
      "passageOffset": [
        155,
        195
      ],
      "spatialClue": {
        "anchorName": "No. 17",
        "bearing": "W",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_28_2",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "Some 100 yards from No. 17 towards north.",
      "passageOffset": [
        984,
        1025
      ],
      "spatialClue": {
        "anchorName": "No. 17",
        "bearing": "N",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_28_3",
      "name": "Gur Duwara, called Bangla Sahib",
      "type": "gateway",
      "period": "Late Mughal",
      "passage": "About half a mile west of Jantar Mantar (No. 24).",
      "passageOffset": [
        1676,
        1725
      ],
      "spatialClue": {
        "anchorName": "Jantar Mantar",
        "bearing": "W",
        "distanceValue": 0.5,
        "distanceUnit": "miles"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_28_3",
      "mentionId": "m_28_3",
      "centroid": [
        77.2083515957974,
        28.627098750556307
      ],
      "uncertaintyRadiusM": 624.4740556618831,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.4953947368421052,
        "parts": {
          "clueSpecificity": 0.5,
          "anchorPrecision": 0.5263157894736842,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "jantar-mantar",
        "anchorName": "Jantar Mantar",
        "anchorSource": "osm:w223456559",
        "anchorCentroid": [
          77.216596,
          28.627099
        ],
        "bearingDeg": 270,
        "distanceM": 804.672,
        "radiusParts": {
          "anchorPrecisionM": 90,
          "bearingSpreadM": 333.30605566188314,
          "distanceVaguenessM": 201.168,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "n11920861769",
            "name": "Pope John-Paul II.",
            "distanceM": 186.90590859028416,
            "insideRadius": true
          },
          {
            "id": "w1137558570",
            "name": "Misra Yantra",
            "distanceM": 784.9884280884779,
            "insideRadius": false
          },
          {
            "id": "w278577239",
            "name": "Gole Market",
            "distanceM": 786.5314862910645,
            "insideRadius": false
          },
          {
            "id": "w1137558567",
            "name": "Jai Prakash Yantra",
            "distanceM": 798.6792184837495,
            "insideRadius": false
          },
          {
            "id": "w500413797",
            "name": "Ram Yantra",
            "distanceM": 802.5410834627056,
            "insideRadius": false
          }
        ]
      }
    }
  ]
};

export default page;
