import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 242,
  "mentions": [
    {
      "id": "m_242_1",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 160 yards from No. 321 to N. W.",
      "passageOffset": [
        531,
        567
      ],
      "spatialClue": {
        "anchorName": "No. 321",
        "bearing": "NW",
        "distanceValue": 160,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_242_2",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Afghan",
      "passage": "Some 175 yards from No- 322 towards west.",
      "passageOffset": [
        1145,
        1186
      ],
      "spatialClue": {
        "anchorName": "No- 322",
        "bearing": "W",
        "distanceValue": 175,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_242_3",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": null,
      "passage": "Some 175 yards from No. 323 to N.-W.",
      "passageOffset": [
        1481,
        1517
      ],
      "spatialClue": {
        "anchorName": "No. 323",
        "bearing": "NW",
        "distanceValue": 175,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
