import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 205,
  "mentions": [
    {
      "id": "m_205_1",
      "name": "^ building",
      "type": "other",
      "period": "Mughal",
      "passage": "Immediately north of No. 259.",
      "passageOffset": [
        393,
        422
      ],
      "spatialClue": {
        "anchorName": "No. 259",
        "bearing": "N",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_205_2",
      "name": "Ruins of some buildings situated in a garden.",
      "type": "garden",
      "period": "Mughal",
      "passage": "150 yards east of Aliganj.",
      "passageOffset": [
        1138,
        1164
      ],
      "spatialClue": {
        "anchorName": "Aliganj",
        "bearing": "E",
        "distanceValue": 150,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_205_3",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": null,
      "passage": "150 yards to the north of the northern gate of Aliganj.",
      "passageOffset": [
        1600,
        1655
      ],
      "spatialClue": {
        "anchorName": "northern gate of Aliganj",
        "bearing": "N",
        "distanceValue": 150,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
