import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 130,
  "mentions": [
    {
      "id": "m_130_1",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "On Delhi-Muttra road, at the junction of the road leading towards the tomb of Safdar Jang.",
      "passageOffset": [
        60,
        150
      ],
      "spatialClue": {
        "anchorName": "Delhi-Muttra road",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_130_2",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 100 yards to the east of No. 142.",
      "passageOffset": [
        546,
        584
      ],
      "spatialClue": {
        "anchorName": "No. 142",
        "bearing": "E",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_130_3",
      "name": "Tomb locally known as Sundarwala Burj",
      "type": "tomb",
      "period": "Mughal",
      "passage": "Some 270 yards from the N. E. corner of Buhalima’s Garden (No. 178), towards the north.",
      "passageOffset": [
        849,
        936
      ],
      "spatialClue": {
        "anchorName": "Buhalima’s Garden",
        "bearing": "N",
        "distanceValue": 270,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_130_4",
      "name": "Tomb locally known as Sundarwala Mahal",
      "type": "tomb",
      "period": null,
      "passage": "Some 270 yards from the N. E. comer of Buhalima’s Garden towards the north, and some 110 yards to the east of No. 148.",
      "passageOffset": [
        1401,
        1519
      ],
      "spatialClue": {
        "anchorName": "Buhalima’s Garden",
        "bearing": "N",
        "distanceValue": 270,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_130_1",
      "mentionId": "m_130_1",
      "centroid": [
        77.245877,
        28.590017
      ],
      "uncertaintyRadiusM": 2650,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.25303846153846155,
        "parts": {
          "clueSpecificity": 0.18,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-muttra-road",
        "anchorName": "Delhi-Muttra Road",
        "anchorSource": "osm:w39013511",
        "anchorCentroid": [
          77.245877,
          28.590017
        ],
        "bearingDeg": null,
        "distanceM": null,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 0,
          "distanceVaguenessM": 150,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w403809796",
            "name": "Mosque",
            "distanceM": 240.3110210678837,
            "insideRadius": true
          },
          {
            "id": "n1754574702",
            "name": "Isa Khan's Tomb",
            "distanceM": 247.87543731514705,
            "insideRadius": true
          },
          {
            "id": "w220385655",
            "name": "Arab Sarai",
            "distanceM": 275.6516524326265,
            "insideRadius": true
          },
          {
            "id": "w163778457",
            "name": "unnamed yes (w163778457)",
            "distanceM": 299.16425699765284,
            "insideRadius": true
          },
          {
            "id": "w163778461",
            "name": "unnamed yes (w163778461)",
            "distanceM": 299.6583176833827,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
