import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 68,
  "mentions": [
    {
      "id": "m_68_1",
      "name": "Tomb (unknown)",
      "type": "tomb",
      "period": "Afghan period",
      "passage": "Some 140 yards to the south of No. 78.",
      "passageOffset": [
        911,
        949
      ],
      "spatialClue": {
        "anchorName": "No. 78",
        "bearing": "S",
        "distanceValue": 140,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_68_2",
      "name": "Grave of Hazrat Bibi Fatima Sam",
      "type": "tomb",
      "period": null,
      "passage": "Some 400 yards to the S.-W. of Khair-ul-Manazil No. 83.",
      "passageOffset": [
        1317,
        1372
      ],
      "spatialClue": {
        "anchorName": "Khair-ul-Manazil No. 83",
        "bearing": "SW",
        "distanceValue": 400,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_68_3",
      "name": "massive gateway",
      "type": "gateway",
      "period": null,
      "passage": "At the distance of some 36 yards towards the west",
      "passageOffset": [
        737,
        786
      ],
      "spatialClue": {
        "anchorName": "tomb",
        "bearing": "W",
        "distanceValue": 36,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_68_4",
      "name": "walled mosque",
      "type": "mosque",
      "period": null,
      "passage": "to its west stands a walled mosque furnished with three mihrabs",
      "passageOffset": null,
      "spatialClue": {
        "anchorName": "tomb",
        "bearing": "W",
        "distanceValue": null,
        "distanceUnit": null
      }
    }
  ],
  "candidates": []
};

export default page;
