import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 253,
  "mentions": [
    {
      "id": "m_253_1",
      "name": "Mosque, Multani Dhanda",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "Some 600 yards to N.-E. of the Dargah of Savyid Hasan Rasul Numa (No. 332).",
      "passageOffset": [
        470,
        545
      ],
      "spatialClue": {
        "anchorName": "the Dargah of Savyid Hasan Rasul Numa",
        "bearing": "NE",
        "distanceValue": 600,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_253_2",
      "name": "Kali Masjid",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "Some 200 yards from the Dargah of Sayyid Hasan Rasul Numa (No. 332) towards north.",
      "passageOffset": [
        1139,
        1221
      ],
      "spatialClue": {
        "anchorName": "the Dargah of Sayyid Hasan Rasul Numa",
        "bearing": "N",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_253_3",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": null,
      "passage": "Some 200 yards from No. 340 towards west.",
      "passageOffset": [
        1840,
        1881
      ],
      "spatialClue": {
        "anchorName": "No. 340",
        "bearing": "W",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
