import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 76,
  "mentions": [
    {
      "id": "m_76_1",
      "name": "An enclosure with two gateways",
      "type": "garden",
      "period": "Mughal",
      "passage": "Immediately to the north of Katra Iradatmand Khan Xo. 95.",
      "passageOffset": [
        70,
        127
      ],
      "spatialClue": {
        "anchorName": "Katra Iradatmand Khan",
        "bearing": "N",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_76_2",
      "name": "Katra Iradatmand Khan",
      "type": "caravanserai",
      "period": "Mughal period",
      "passage": "Some 100 yards to the west of No. 200, outside Kotla Nizamuddin.",
      "passageOffset": [
        600,
        664
      ],
      "spatialClue": {
        "anchorName": "Kotla Nizamuddin",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_76_3",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "Some 33 yards to the east of Katra Iradatmand Khan No. 95.",
      "passageOffset": [
        1372,
        1430
      ],
      "spatialClue": {
        "anchorName": "Katra Iradatmand Khan",
        "bearing": "E",
        "distanceValue": 33,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
