import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 79,
  "mentions": [
    {
      "id": "m_79_1",
      "name": "Unknown",
      "type": "other",
      "period": "Mughal",
      "passage": "",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": null
    },
    {
      "id": "m_79_2",
      "name": "Gurdwara",
      "type": "temple",
      "period": "Late Mughal",
      "passage": "Some 500 yards to the north of No. 102 and some 300 yards to tlie south of No. 105.",
      "passageOffset": [
        422,
        505
      ],
      "spatialClue": {
        "anchorName": "No. 102",
        "bearing": "N",
        "distanceValue": 500,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_79_3",
      "name": "Unknown",
      "type": "mosque",
      "period": "Afghan period",
      "passage": "Some 25 yards to the north of No. 103.",
      "passageOffset": [
        890,
        928
      ],
      "spatialClue": {
        "anchorName": "No. 103",
        "bearing": "N",
        "distanceValue": 25,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_79_4",
      "name": "Chaunsath Khamba",
      "type": "mosque",
      "period": null,
      "passage": "About half a mile to the S. E. of the Turkman gate of Shahjahanabad, and some 300^ards to the east of the slaughter house.",
      "passageOffset": [
        1281,
        1403
      ],
      "spatialClue": {
        "anchorName": "Turkman gate of Shahjahanabad",
        "bearing": "SE",
        "distanceValue": 0.5,
        "distanceUnit": "miles"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_79_4",
      "mentionId": "m_79_4",
      "centroid": [
        77.23850723301179,
        28.637159841017827
      ],
      "uncertaintyRadiusM": 569.4740556618831,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.5597222222222222,
        "parts": {
          "clueSpecificity": 0.5,
          "anchorPrecision": 0.7407407407407407,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "turkman-gate",
        "anchorName": "Turkman Gate",
        "anchorSource": "osm:w973086053",
        "anchorCentroid": [
          77.232677,
          28.642277
        ],
        "bearingDeg": 135,
        "distanceM": 804.672,
        "radiusParts": {
          "anchorPrecisionM": 35,
          "bearingSpreadM": 333.30605566188314,
          "distanceVaguenessM": 201.168,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w464253914",
            "name": "Khooni Darwaza",
            "distanceM": 277.00452114773384,
            "insideRadius": true
          },
          {
            "id": "w1454838166",
            "name": "Mahilla Haat",
            "distanceM": 417.1739399971409,
            "insideRadius": true
          },
          {
            "id": "w973086052",
            "name": "unnamed citywalls (w973086052)",
            "distanceM": 490.0932281369821,
            "insideRadius": true
          },
          {
            "id": "w973086054",
            "name": "Delhi Gate",
            "distanceM": 490.0932281369821,
            "insideRadius": true
          },
          {
            "id": "w1256902982",
            "name": "unnamed ruins (w1256902982)",
            "distanceM": 528.4328862242808,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
