import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 280,
  "mentions": [
    {
      "id": "m_280_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "About 300 yards to the south of the village, on the further side of the\nR. M. Railway.",
      "passageOffset": [
        56,
        142
      ],
      "spatialClue": {
        "anchorName": "village",
        "bearing": "S",
        "distanceValue": 300,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_280_2",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "About 30 yards to the south of No. 378.",
      "passageOffset": [
        1002,
        1041
      ],
      "spatialClue": {
        "anchorName": "No. 378",
        "bearing": "S",
        "distanceValue": 30,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_280_3",
      "name": "Unknown",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "About 500 yards from the village towards the west.",
      "passageOffset": [
        1500,
        1550
      ],
      "spatialClue": {
        "anchorName": "village",
        "bearing": "W",
        "distanceValue": 500,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
