import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 35,
  "mentions": [
    {
      "id": "m_35_1",
      "name": "Agra Yantra",
      "type": "other",
      "period": null,
      "passage": "On the west side of the building is a second quadrant, the face of which is horizontal instead of being parallel to the axis. It is called the Agra Yantra or amplitude instrument,",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "building",
        "bearing": "W",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_35_2",
      "name": "Dakshinavritti Yantras",
      "type": "other",
      "period": null,
      "passage": "On the east wall of the building is a graduated semi-circle called Dakshinavritti Yantras, used for obtaining meridian altitudes.",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "building",
        "bearing": "E",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_35_3",
      "name": "Karka Rasi Valaya",
      "type": "other",
      "period": null,
      "passage": "The north wall of the Misra Yantra is inclined to the vertical at an angle of 5 degrees, and is marked ... This is called the Karka Rasi Valaya, or “ Circle of the sign of Cancer.”",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "Misra Yantra",
        "bearing": "N",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_35_4",
      "name": "Two pillars",
      "type": "other",
      "period": null,
      "passage": "To the south-west of the Misra Yantra are two pillars 17 feet apart, and the line joining their centres points 35° east of north.",
      "passageOffset": [
        1949,
        2078
      ],
      "spatialClue": {
        "anchorName": "Misra Yantra",
        "bearing": "SW",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_35_5",
      "name": "small building (a chowkidar’s house)",
      "type": "other",
      "period": null,
      "passage": "To the west of the Samrat Yantra is a small building (a chowkidar’s house) on which is fixed the Jaipur flag.",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "Samrat Yantra",
        "bearing": "W",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_35_6",
      "name": "tree",
      "type": "other",
      "period": null,
      "passage": "There is a tree south-east of the eastern Jai Prakas that partially overshadows that instrument.",
      "passageOffset": [
        2729,
        2825
      ],
      "spatialClue": {
        "anchorName": "eastern Jai Prakas",
        "bearing": "SE",
        "distanceValue": null,
        "distanceUnit": null
      }
    }
  ],
  "candidates": []
};

export default page;
