import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 77,
  "mentions": [
    {
      "id": "m_77_1",
      "name": "Unknown",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "At the first mile-stone on Delhi-Muttra Road.",
      "passageOffset": [
        68,
        113
      ],
      "spatialClue": {
        "anchorName": "the first mile-stone on Delhi-Muttra Road",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_77_2",
      "name": "Bastion",
      "type": "other",
      "period": "Sher Shah(?)",
      "passage": "Some 100 yards to the west of No. 97.",
      "passageOffset": [
        356,
        393
      ],
      "spatialClue": {
        "anchorName": "No. 97",
        "bearing": "W",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_77_3",
      "name": "Unknown",
      "type": "mosque",
      "period": "Afghan",
      "passage": "Within the compound of the Reformatory school, some 100 yards to the S.-E. of the District Jail (No. 100).",
      "passageOffset": [
        683,
        789
      ],
      "spatialClue": {
        "anchorName": "the Reformatory school",
        "bearing": "within",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_77_4",
      "name": "Sarai of Nawab Shaikh Farid Khan, known as Murtaza Khan",
      "type": "caravanserai",
      "period": null,
      "passage": "About half a mile to the south of the Delhi gate of Shahjahanabad, occupying the centre of the enclosure of the District jail.",
      "passageOffset": [
        1174,
        1300
      ],
      "spatialClue": {
        "anchorName": "the Delhi gate of Shahjahanabad",
        "bearing": "S",
        "distanceValue": 0.5,
        "distanceUnit": "miles"
      }
    }
  ],
  "candidates": []
};

export default page;
