import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 55,
  "mentions": [
    {
      "id": "m_55_1",
      "name": "Baoli, Mosque and four walls of an enclosed garden, with its entrance",
      "type": "mosque",
      "period": "Mughal",
      "passage": "(6) Some 180 yards to the east of No. 47 and 110 yards to the north of No. 49.",
      "passageOffset": [
        1401,
        1479
      ],
      "spatialClue": {
        "anchorName": "No. 47",
        "bearing": "E",
        "distanceValue": 180,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_55_2",
      "name": "Tomb of Sikandar Lodi",
      "type": "tomb",
      "period": "923 A.H. (1517-8 A.D.)",
      "passage": "(6) Some 250 yards to north-east of No. 47.",
      "passageOffset": [
        2087,
        2130
      ],
      "spatialClue": {
        "anchorName": "No. 47",
        "bearing": "NE",
        "distanceValue": 250,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": []
};

export default page;
