import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 198,
  "mentions": [
    {
      "id": "m_198_1",
      "name": "Tomb of Khani Jahan Khan Tilangani.",
      "type": "tomb",
      "period": "Tughlaq",
      "passage": "(b) Village of Nizamuddin, at N. W. corner of the inner Kot (No. 241).",
      "passageOffset": [
        72,
        142
      ],
      "spatialClue": {
        "anchorName": "inner Kot",
        "bearing": "NW",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_198_2",
      "name": "Bridge",
      "type": "bridge",
      "period": "Afghan",
      "passage": "(b) Some 50 yards from the wall of the village of Nizamuddin and against the tomb of Khan Jahan Tilangani (No. 242)), towards north-west.",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "wall of the village of Nizamuddin",
        "bearing": "NW",
        "distanceValue": 50,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_198_3",
      "name": "Dome Sanjarwala (Sanjar’s dome).",
      "type": "other",
      "period": "Mughal",
      "passage": "(b) Some 500 yards to the west of Khan Khanan’s tomb (No. 169) and 400 yards to the south of Kotla Nizamuddin.",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": {
        "anchorName": "Khan Khanan’s tomb",
        "bearing": "W",
        "distanceValue": 500,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_198_3",
      "mentionId": "m_198_3",
      "centroid": [
        77.24333941977898,
        28.588060919602366
      ],
      "uncertaintyRadiusM": 327.95844071697906,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.6489705882352941,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.5882352941176471,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "khan-khanan-tomb",
        "anchorName": "Khan Khanan's Tomb",
        "anchorSource": "osm:n1754574641",
        "anchorCentroid": [
          77.248022,
          28.588061
        ],
        "bearingDeg": 270,
        "distanceM": 457.2,
        "radiusParts": {
          "anchorPrecisionM": 70,
          "bearingSpreadM": 189.37844071697904,
          "distanceVaguenessM": 68.58,
          "floorTopUpM": 0
        },
        "baselineVerdict": "representation_gap",
        "baselineChecked": [
          {
            "id": "w103505910",
            "name": "Chausath Khamba",
            "distanceM": 349.86048989811417,
            "insideRadius": false
          },
          {
            "id": "n1195165037",
            "name": "Mirza Ghalib's Tomb",
            "distanceM": 375.78144632084116,
            "insideRadius": false
          },
          {
            "id": "w103505909",
            "name": "Nizamuddin Dargah",
            "distanceM": 392.2772154559582,
            "insideRadius": false
          },
          {
            "id": "w1361098049",
            "name": "Nizamuddin Dargah Complex",
            "distanceM": 395.92973833843286,
            "insideRadius": false
          },
          {
            "id": "n7040397189",
            "name": "Ataga Khan's Tomb",
            "distanceM": 402.19678330628057,
            "insideRadius": false
          }
        ]
      }
    }
  ]
};

export default page;
