import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 35,
  "mentions": [
    {
      "id": "m_35_1",
      "name": "two pillars",
      "type": "other",
      "period": null,
      "passage": "To the south-west of the Misra Yantra",
      "passageOffset": [
        1949,
        1986
      ],
      "spatialClue": {
        "anchorName": "Misra Yantra",
        "bearing": "SW",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_35_2",
      "name": "wall",
      "type": "other",
      "period": null,
      "passage": "to the west of the Misra Yantra",
      "passageOffset": [
        2299,
        2330
      ],
      "spatialClue": {
        "anchorName": "Misra Yantra",
        "bearing": "W",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_35_3",
      "name": "small building (a chowkidar’s house)",
      "type": "other",
      "period": null,
      "passage": "To the \\vest of the Samrat Yantra",
      "passageOffset": [
        2618,
        2651
      ],
      "spatialClue": {
        "anchorName": "Samrat Yantra",
        "bearing": "W",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_35_4",
      "name": "tree",
      "type": "other",
      "period": null,
      "passage": "south-east of the eastern Jai Prakas",
      "passageOffset": [
        2745,
        2781
      ],
      "spatialClue": {
        "anchorName": "Jai Prakas",
        "bearing": "SE",
        "distanceValue": null,
        "distanceUnit": null
      }
    }
  ],
  "candidates": []
};

export default page;
