// generated by scripts/pull-zones.ts from OpenStreetMap way 80429794, ODbL
export const source = "OpenStreetMap way 80429794, ODbL";
export const centroid: [number, number] = [77.242348,28.655718];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2421705, 28.6559661],
      [77.2423966, 28.6559566],
      [77.2423883, 28.655804],
      [77.242496, 28.6557994],
      [77.2424928, 28.6557254],
      [77.2424855, 28.6556084],
      [77.2423781, 28.655613],
      [77.2423708, 28.6554789],
      [77.2421442, 28.6554885],
      [77.242158, 28.65574],
      [77.2421705, 28.6559661],
    ],
  ],
};
