// generated by scripts/pull-zones.ts from OpenStreetMap way 223903623, ODbL
export const source = "OpenStreetMap way 223903623, ODbL";
export const centroid: [number, number] = [77.243142,28.656848];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2430434, 28.6569142],
      [77.2432438, 28.656911],
      [77.2432411, 28.6567821],
      [77.2430408, 28.6567853],
      [77.2430434, 28.6569142],
    ],
  ],
};
