// generated by scripts/pull-zones.ts from OpenStreetMap way 80429887, ODbL
export const source = "OpenStreetMap way 80429887, ODbL";
export const centroid: [number, number] = [77.243645,28.656127];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2434515, 28.6560506],
      [77.2436594, 28.6560414],
      [77.2436614, 28.6560773],
      [77.2437003, 28.6560749],
      [77.2437391, 28.656099],
      [77.2437412, 28.6561449],
      [77.2437056, 28.6561744],
      [77.2436667, 28.6561755],
      [77.2436683, 28.6562137],
      [77.2434605, 28.6562228],
      [77.2434515, 28.6560506],
    ],
  ],
};
