// generated by scripts/pull-zones.ts from OpenStreetMap way 320353003, ODbL
export const source = "OpenStreetMap way 320353003, ODbL";
export const centroid: [number, number] = [77.242936,28.657758];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2423453, 28.6585934],
      [77.2436284, 28.6585527],
      [77.2435208, 28.6569158],
      [77.2422511, 28.6569682],
      [77.2423453, 28.6585934],
    ],
  ],
};
