// generated by scripts/pull-zones.ts from OpenStreetMap way 80429830, ODbL
export const source = "OpenStreetMap way 80429830, ODbL";
export const centroid: [number, number] = [77.243576,28.656472];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2434592, 28.6563407],
      [77.2436789, 28.6563337],
      [77.2436937, 28.6566024],
      [77.243474, 28.6566094],
      [77.2434592, 28.6563407],
    ],
  ],
};
