// generated by scripts/pull-zones.ts from OpenStreetMap way 80429907, ODbL
export const source = "OpenStreetMap way 80429907, ODbL";
export const centroid: [number, number] = [77.238736,28.655879];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2388234, 28.6556722],
      [77.2386053, 28.6556782],
      [77.238607, 28.6557146],
      [77.2386161, 28.6559082],
      [77.2386272, 28.6561199],
      [77.2388452, 28.6561139],
      [77.2388408, 28.6560255],
      [77.2388346, 28.6558996],
      [77.2388288, 28.6557806],
      [77.2388234, 28.6556722],
    ],
  ],
};
