// generated by scripts/pull-zones.ts from OpenStreetMap way 80429900, ODbL
export const source = "OpenStreetMap way 80429900, ODbL";
export const centroid: [number, number] = [77.240992,28.655792];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2409253, 28.655928],
      [77.2410758, 28.6559208],
      [77.241068, 28.6557954],
      [77.2410591, 28.6556502],
      [77.2409087, 28.6556573],
      [77.2409174, 28.6558016],
      [77.2409253, 28.655928],
    ],
  ],
};
