// generated by scripts/pull-zones.ts from OpenStreetMap way 223903620, ODbL
export const source = "OpenStreetMap way 223903620, ODbL";
export const centroid: [number, number] = [77.243493,28.656781];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2434965, 28.6567153],
      [77.2437066, 28.6567091],
      [77.2437137, 28.6568931],
      [77.2433159, 28.6569048],
      [77.2433112, 28.6567813],
      [77.2434523, 28.6567772],
      [77.2434506, 28.6567329],
      [77.2434972, 28.6567315],
      [77.2434965, 28.6567153],
    ],
  ],
};
