// generated by scripts/pull-zones.ts from OpenStreetMap way 80429815, ODbL
export const source = "OpenStreetMap way 80429815, ODbL";
export const centroid: [number, number] = [77.243423,28.654524];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2432932, 28.6546582],
      [77.2435667, 28.6546479],
      [77.2435521, 28.6543896],
      [77.2432785, 28.6543998],
      [77.2432932, 28.6546582],
    ],
  ],
};
