// generated by scripts/pull-zones.ts from OpenStreetMap way 80429915, ODbL
export const source = "OpenStreetMap way 80429915, ODbL";
export const centroid: [number, number] = [77.243528,28.65568];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2434234, 28.6559064],
      [77.2436607, 28.6558953],
      [77.2436318, 28.6554533],
      [77.2433945, 28.6554643],
      [77.2434234, 28.6559064],
    ],
  ],
};
