// generated by scripts/pull-zones.ts from OpenStreetMap way 80429800, ODbL
export const source = "OpenStreetMap way 80429800, ODbL";
export const centroid: [number, number] = [77.239311,28.655882];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2398302, 28.6559845],
      [77.2398231, 28.655856],
      [77.2398171, 28.6557399],
      [77.2392491, 28.6557631],
      [77.2388288, 28.6557806],
      [77.2388346, 28.6558996],
      [77.2388408, 28.6560255],
      [77.2392634, 28.6560086],
      [77.2398302, 28.6559845],
    ],
  ],
};
