import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { ANCHORS } from "@/content/anchors";
import type { BaselineFeature } from "@/lib/discovery/baseline";
import { buildCandidates } from "@/lib/discovery/candidates";
import { extractMentions } from "@/lib/discovery/extract";
import type { AnalyseResult } from "@/lib/types";

// The cache is the fallback the demo leans on, so it is built before the screen that reads it.
// plan/05 decision 6. Run with:
//   npx tsx --env-file=.env.local scripts/build-discovery-cache.ts           every Page
//   npx tsx --env-file=.env.local scripts/build-discovery-cache.ts missing   only the gaps
//   npx tsx --env-file=.env.local scripts/build-discovery-cache.ts 145       one Page

const VOLUME_ID = "zafar-hasan-v2";
const OUT_DIR = "content/discovery-cache";

// Groq's free tier binds on tokens, not requests: 8000 a minute, and one Page costs
// roughly 2000 once the model's reasoning tokens are counted
const PAUSE_MS = 25_000;
const RETRY_WAIT_MS = 65_000;

interface Page {
  pageNo: number;
  printedPageNo: number | null;
  imageUrl: string;
  clueScore: number;
  text: string;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function fileFor(pageNo: number): string {
  return `${OUT_DIR}/${VOLUME_ID}-${pageNo}.ts`;
}

// a typed module rather than JSON, the same way content/zones does it. importing JSON widens
// tuples to number[] and enums to string, and the cast that hides it would be a lie
function moduleFor(result: AnalyseResult): string {
  return [
    'import type { AnalyseResult } from "@/lib/types";',
    "",
    "// generated by scripts/build-discovery-cache.ts",
    `const page: AnalyseResult = ${JSON.stringify(result, null, 2)};`,
    "",
    "export default page;",
    "",
  ].join("\n");
}

async function main() {
  const volume = JSON.parse(await readFile(`content/pages/${VOLUME_ID}.json`, "utf8")) as { pages: Page[] };
  const baseline = JSON.parse(await readFile("content/baseline.geojson", "utf8")) as { features: BaselineFeature[] };
  await mkdir(OUT_DIR, { recursive: true });

  const arg = process.argv[2];
  const already = new Set((await readdir(OUT_DIR)).filter((f) => f.endsWith(".ts") && f !== "index.ts"));
  let pages = volume.pages;
  if (arg === "missing") pages = pages.filter((p) => !already.has(`${VOLUME_ID}-${p.pageNo}.ts`));
  else if (arg) pages = pages.filter((p) => p.pageNo === Number(arg));

  console.log(`${pages.length} Pages to read\n`);
  let done = 0;
  const failed: number[] = [];

  for (const page of pages) {
    let extracted = await extractMentions(page.pageNo, page.text);
    if (!extracted.ok) {
      // the rate limit resets on the minute, so one wait is usually all it takes
      console.log(`p${page.pageNo}\twaiting on ${extracted.reason}`);
      await sleep(RETRY_WAIT_MS);
      extracted = await extractMentions(page.pageNo, page.text);
    }
    if (!extracted.ok) {
      failed.push(page.pageNo);
      console.log(`p${page.pageNo}\tFAILED\t${extracted.reason}`);
      await sleep(PAUSE_MS);
      continue;
    }

    const { mentions, modelId } = extracted.extraction;
    const candidates = buildCandidates({ mentions, anchors: ANCHORS, baseline: baseline.features, volumeId: VOLUME_ID });
    const result: AnalyseResult = { source: "cached", modelId, pageNo: page.pageNo, mentions, candidates };

    await writeFile(fileFor(page.pageNo), moduleFor(result));
    done++;

    const by = (v: string) => candidates.filter((c) => c.evidence.baselineVerdict === v).length;
    const lost = mentions.filter((m) => m.passageOffset === null).length;
    console.log(
      `p${page.pageNo}\t${mentions.length} mentions\t${candidates.length} placed\t` +
        `${by("representation_gap")} gap\t${by("matched_existing")} matched\t${by("inconclusive")} unclear\t` +
        `${mentions.length - candidates.length} partial\t${lost} unhighlighted`,
    );
    await sleep(PAUSE_MS);
  }

  await writeBarrel();
  console.log(`\nwrote ${done} Pages`);
  if (failed.length) console.log(`still missing: ${failed.join(", ")}`);
}

// a static barrel rather than a runtime file read, because this is the fallback the demo
// leans on and an import cannot go missing from a deploy
async function writeBarrel() {
  const files = (await readdir(OUT_DIR))
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .sort((a, b) => Number(a.match(/-(\d+)\.ts$/)?.[1]) - Number(b.match(/-(\d+)\.ts$/)?.[1]));
  const key = (f: string) => f.replace(/\.ts$/, "");
  const body = [
    'import type { AnalyseResult } from "@/lib/types";',
    "",
    ...files.map((f, i) => `import p${i} from "./${key(f)}";`),
    "",
    "// generated by scripts/build-discovery-cache.ts",
    "export const DISCOVERY_CACHE: Record<string, AnalyseResult> = {",
    ...files.map((f, i) => `  "${key(f)}": p${i},`),
    "};",
    "",
  ].join("\n");
  await writeFile(`${OUT_DIR}/index.ts`, body);
  console.log(`barrel: ${files.length} Pages`);
}

main();
